apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "Missing fullnameOverride" .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ required "Missing fullnameOverride" .Values.fullnameOverride }}
          image: "{{ required "Missing image.repository" (.Values.image).repository }}:{{ required "Missing image.tag" (.Values.image).tag }}"
          imagePullPolicy: {{ required "Missing image.pullPolicy" (.Values.image).pullPolicy }}
          ports:
            - containerPort: {{ required "Missing ports.http" (.Values.ports).http }}
          # Use ConfigMap to configure phpPgAdmin and Apache
          # See: https://kubernetes.io/docs/concepts/configuration/configmap/#using-configmaps-as-files-from-a-pod
          volumeMounts:
            - name: config-volume
              mountPath: /etc/apache2/conf-available/phppgadmin.conf
              subPath: phppgadmin.conf
            - name: config-volume
              mountPath: /etc/phppgadmin/config.inc.php
              subPath: config.inc.php
      volumes:
        - name: config-volume
          configMap:
            name: {{ required "Missing fullnameOverride" .Values.fullnameOverride }}-config
