apiVersion: v1
kind: Service
metadata:
  name: {{ required "Missing fullnameOverride" .Values.fullnameOverride }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ required "Missing ports.http" (.Values.ports).http }}
      targetPort: 80
