apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "Missing fullnameOverride" .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ required "Missing fullnameOverride" .Values.fullnameOverride }}
          image: "{{ required "Missing image.repository" (.Values.image).repository }}:{{ required "Missing image.tag" (.Values.image).tag }}"
          imagePullPolicy: {{ required "Missing image.pullPolicy" (.Values.image).pullPolicy }}
          ports:
            - containerPort: {{ required "Missing ports.http" (.Values.ports).http }}
          envFrom:
            - secretRef:
                name: {{ required "Missing secretName" .Values.secretName }}
                optional: false
          command:
          - fastapi
          - run
          args:
          - --host
          - 0.0.0.0
          - --port
          - "8000"
          - --root-path
          - {{ required "Missing pathPrefix" .Values.pathPrefix }}
          - src/dtp/auth/app.py
