# See the chart's values.yaml for all configurable parameters and their default values.
fullnameOverride: "phppgadmin"
image:
  tag: "latest"

service:
  type: NodePort

ports:
  http:
    nodePort: 30100
