# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Use `just pre-commit-update` to update to the latest versions of the hooks

# Install hooks for the pre-commit and pre-push stages by default
default_install_hook_types: [pre-commit, pre-push]

# Exclude VSCode settings directory
exclude: ^(.vscode/).*

# Define the hooks to run
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--allow-multiple-documents', '--unsafe']
    # Exclude Helm chart templates from YAML checks, as they are Go templates, not pure YAML
    exclude: templates/.*
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
    # Permit non-root redirects when using 'sudo' in scripts
    # e.g. `sudo microk8s config > ~/.kube/config`
    # Use `| sudo tee <file> > /dev/null` to write as root
    args: ['-e', 'SC2024']
- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
    args: ['-conf', 'configs/yamlfmt.yaml']
    # Exclude Helm chart templates from YAML checks, as they are Go templates, not pure YAML
    exclude: templates/.*
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.18.1
  hooks:
  - id: markdownlint-cli2
    args: ['--config', 'configs/.markdownlint.yaml', '--fix']
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30
  hooks:
  - id: helmlint
