# Traefik configuration
# See: https://doc.traefik.io/traefik/getting-started/quick-start-with-kubernetes/

deployment:
  kind: DaemonSet

# For local microk8s, use ClusterIP and forward the ports manually
# For cloud environments, consider using LoadBalancer
service:
  type: ClusterIP

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    entryPoints:
    - web

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
