# Traefik configuration
# See: https://doc.traefik.io/traefik/getting-started/quick-start-with-kubernetes/

deployment:
  kind: DaemonSet

service:
  type: NodePort

ports:
  web:
    nodePort: 30080
  traefik:
    nodePort: 30081
    expose:
      default: true
  # Disable the secure port as we don't have TLS set up yet
  websecure:
    nodePort: 30443
    expose:
      default: false

ingressRoute:
  dashboard:
    enabled: true
    matchRule: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    entryPoints:
    - traefik

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
